org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# NOTE: Flutter template thêm cờ newDsl này.
android.newDsl=false
# NOTE: Flutter template thêm cờ builtInKotlin này.
android.builtInKotlin=false
# FIXME: Tránh lỗi biên dịch tăng dần Kotlin khác ổ đĩa trên Windows (C: và D:).
kotlin.incremental=false
kotlin.incremental.java=false
